name: Test find_lowest_number.py

on:
  push: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Run tests
        run: |
          python3 find_lowest_number.py test_data/test1_input.txt test_output1.txt
          diff test_output1.txt test_data/test1_expected.txt

          python3 find_lowest_number.py test_data/test2_input.txt test_output2.txt
          diff test_output2.txt test_data/test2_expected.txt

          python3 find_lowest_number.py test_data/test3_input.txt test_output3.txt
          diff test_output3.txt test_data/test3_expected.txt

          # Remove temporary output files
          rm test_output1.txt test_output2.txt test_output3.txt
